apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: time-service
  name: time-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: time-service
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: time-service
    spec:
      containers:
      - image: ivanporty/time-service:0.1.0
        name: time-service
        resources: {}
status: {}
